import type { Language } from '../types';

type TranslationKey =
  | 'dashboard'
  | 'ragDatabaseManagement'
  | 'modules'
  | 'worksContractTenderModule'
  | 'manageTenderProcesses'
  | 'consultancyAssignmentModule'
  | 'handleConsultancyTasks'
  | 'contractualQueryModule'
  | 'resolveContractInquiries'
  | 'activeUsers'
  | 'load'
  | 'publicDatabase'
  | 'personalDatabase'
  | 'lastUpdated'
  | 'documents'
  | 'totalSize'
  | 'uploadToRAG'
  | 'accessTemplates'
  | 'viewAnalytics'
  | 'typeMessage'
  | 'newChat'
  | 'active'
  | 'updating'
  | 'notice';

type TranslationDictionary = {
  [key in TranslationKey]: string;
};

type Translations = {
  [key in Language]: TranslationDictionary;
};

export const translations: Translations = {
  'en': {
    dashboard: 'Dashboard',
    ragDatabaseManagement: 'RAG Database Management',
    modules: 'Modules',
    worksContractTenderModule: 'Works Contract Tender Module',
    manageTenderProcesses: 'Manage tender processes',
    consultancyAssignmentModule: 'Consultancy Assignment Module',
    handleConsultancyTasks: 'Handle consultancy tasks',
    contractualQueryModule: 'Contractual Query Module',
    resolveContractInquiries: 'Resolve contract inquiries',
    activeUsers: 'active',
    load: 'load',
    publicDatabase: 'Public Database',
    personalDatabase: 'Personal Database',
    lastUpdated: 'Last updated',
    documents: 'Documents',
    totalSize: 'Total size',
    uploadToRAG: 'Upload to RAG Database',
    accessTemplates: 'Access Templates',
    viewAnalytics: 'View Analytics',
    typeMessage: 'Type your message...',
    newChat: 'New Chat',
    active: 'Active',
    updating: 'Updating',
    notice: 'The content is generated by AI and is for reference only'
  },
  'zh-CN': {
    dashboard: '仪表板',
    ragDatabaseManagement: 'RAG数据库管理',
    modules: '模块',
    worksContractTenderModule: '工程合同招标模块',
    manageTenderProcesses: '管理招标流程',
    consultancyAssignmentModule: '咨询任务模块',
    handleConsultancyTasks: '处理咨询任务',
    contractualQueryModule: '合同查询模块',
    resolveContractInquiries: '解决合同查询',
    activeUsers: '活跃用户',
    load: '负载',
    publicDatabase: '公共数据库',
    personalDatabase: '个人数据库',
    lastUpdated: '最后更新',
    documents: '文档',
    totalSize: '总大小',
    uploadToRAG: '上传至RAG数据库',
    accessTemplates: '访问模板',
    viewAnalytics: '查看分析',
    typeMessage: '输入消息...',
    newChat: '新对话',
    active: '活跃',
    updating: '更新中',
    notice: '内容由AI生成，仅供参考'
  },
  'zh-TW': {
    dashboard: '儀表板',
    ragDatabaseManagement: 'RAG資料庫管理',
    modules: '模組',
    worksContractTenderModule: '工程合約招標模組',
    manageTenderProcesses: '管理招標流程',
    consultancyAssignmentModule: '諮詢任務模組',
    handleConsultancyTasks: '處理諮詢任務',
    contractualQueryModule: '合約查詢模組',
    resolveContractInquiries: '解決合約查詢',
    activeUsers: '活躍用戶',
    load: '負載',
    publicDatabase: '公共資料庫',
    personalDatabase: '個人資料庫',
    lastUpdated: '最後更新',
    documents: '文件',
    totalSize: '總大小',
    uploadToRAG: '上傳至RAG資料庫',
    accessTemplates: '訪問模板',
    viewAnalytics: '查看分析',
    typeMessage: '輸入訊息...',
    newChat: '新對話',
    active: '活躍',
    updating: '更新中',
    notice: '內容由AI生成，僅供參考'
  }
};

export function getTranslation(key: TranslationKey, language: Language): string {
  return translations[language][key] || translations['en'][key] || key;
}